version: 2

updates:

  - package-ecosystem: "npm"
    directory: "./"
    open-pull-requests-limit: 2
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: "Pacific/Auckland"
